export const REQUEST_LIST_TODOS = "REQUEST_LIST_TODOS";
export const REQUEST_LIST_TODOS_SUCCESS = "REQUEST_LIST_TODOS_SUCCESS";
export const REQUEST_LIST_TODOS_FAILED = "REQUEST_LIST_TODOS_FAILED";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_FAILED = "REQUEST_LOGIN_FAILED";

export const REQUEST_LOGOUT = "REQUEST_LOGOUT";

export const REQUEST_GET_PROFILE = "REQUEST_GET_PROFILE";
export const REQUEST_GET_PROFILE_SUCCESS = "REQUEST_GET_PROFILE_SUCCESS";
export const REQUEST_GET_PROFILE_FAILED = "REQUEST_GET_PROFILE_FAILED";
