export const RouteBase = {
    Home: '/',
    UserManager: '/quan-ly-user',
    OrgManager: '/quan-ly-org',
    RegisterMember: '/register-member',
    Profile: '/profile',
    UpdatePassword: '/update-password',
    Dashboard: '/dashboard',
    DashboardORG: '/dashboard-org',
    NotificationManager: '/quan-ly-thong-bao',
    NotificationSending: '/gui-thong-bao',
    GrantAccess: '/phan-quyen',
    PointManagement: '/quan-ly-diem-cuu-tro',
    AccountManagement: '/quan-ly-tai-khoan',
    CreateEvent: '/them-moi-su-kien',
    EventManagement: '/danh-sach-su-kien',
    EventAssign: '/quan-ly-thanh-vien-su-kien',
};
